/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export interface Category { 'id' : CategoryId, 'name' : string }
export type CategoryId = bigint;
export interface Order {
  'id' : OrderId,
  'total' : bigint,
  'user' : Principal,
  'address' : string,
  'timestamp' : bigint,
  'items' : Array<[ProductId, bigint]>,
}
export type OrderId = bigint;
export interface Product {
  'id' : ProductId,
  'categoryId' : CategoryId,
  'title' : string,
  'views' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'stock' : bigint,
  'purchases' : bigint,
  'price' : bigint,
}
export type ProductId = bigint;
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[string], CategoryId>,
  'addProduct' : ActorMethod<
    [string, string, bigint, bigint, CategoryId],
    ProductId
  >,
  'addToCart' : ActorMethod<[ProductId, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkout' : ActorMethod<[string], OrderId>,
  'clearCart' : ActorMethod<[], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'filterProductsByCategory' : ActorMethod<[CategoryId], Array<Product>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getCartTotal' : ActorMethod<[], bigint>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getOrderHistory' : ActorMethod<[], Array<Order>>,
  'getOrdersByUser' : ActorMethod<[Principal], Array<Order>>,
  'getPopularProducts' : ActorMethod<[bigint], Array<Product>>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCategories' : ActorMethod<[], Array<Category>>,
  'listProducts' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Product>>,
  'removeFromCart' : ActorMethod<[ProductId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updateCartQuantity' : ActorMethod<[ProductId, bigint], undefined>,
  'updateProduct' : ActorMethod<
    [ProductId, string, string, bigint, bigint, CategoryId],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];