/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CategoryId = IDL.Nat;
export const ProductId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'categoryId' : CategoryId,
  'title' : IDL.Text,
  'views' : IDL.Nat,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'purchases' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'total' : IDL.Nat,
  'user' : IDL.Principal,
  'address' : IDL.Text,
  'timestamp' : IDL.Int,
  'items' : IDL.Vec(IDL.Tuple(ProductId, IDL.Nat)),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const Category = IDL.Record({ 'id' : CategoryId, 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([IDL.Text], [CategoryId], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, CategoryId],
      [ProductId],
      [],
    ),
  'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkout' : IDL.Func([IDL.Text], [OrderId], []),
  'clearCart' : IDL.Func([], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'filterProductsByCategory' : IDL.Func(
      [CategoryId],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getCartTotal' : IDL.Func([], [IDL.Nat], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrdersByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getPopularProducts' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'listProducts' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'removeFromCart' : IDL.Func([ProductId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateCartQuantity' : IDL.Func([ProductId, IDL.Nat], [], []),
  'updateProduct' : IDL.Func(
      [ProductId, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, CategoryId],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CategoryId = IDL.Nat;
  const ProductId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'categoryId' : CategoryId,
    'title' : IDL.Text,
    'views' : IDL.Nat,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'purchases' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'total' : IDL.Nat,
    'user' : IDL.Principal,
    'address' : IDL.Text,
    'timestamp' : IDL.Int,
    'items' : IDL.Vec(IDL.Tuple(ProductId, IDL.Nat)),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const Category = IDL.Record({ 'id' : CategoryId, 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([IDL.Text], [CategoryId], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, CategoryId],
        [ProductId],
        [],
      ),
    'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkout' : IDL.Func([IDL.Text], [OrderId], []),
    'clearCart' : IDL.Func([], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'filterProductsByCategory' : IDL.Func(
        [CategoryId],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getCartTotal' : IDL.Func([], [IDL.Nat], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrdersByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getPopularProducts' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'listProducts' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'removeFromCart' : IDL.Func([ProductId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'updateCartQuantity' : IDL.Func([ProductId, IDL.Nat], [], []),
    'updateProduct' : IDL.Func(
        [ProductId, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, CategoryId],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };